name: "Flutter setup"
description: "Setup flutter"
inputs:
  ENCRYPTED_SIGNETS_API_CERT_PASSWORD:
    required: true
  ENCRYPTED_GOOGLE_SERVICE_PASSWORD:
    required: true
  ENCRYPTED_ETSMOBILE_KEYSTORE_PASSWORD:
    required: true
  ENCRYPTED_KEYSTORE_PROPERTIES_PASSWORD:
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.x'
        channel: 'stable'
        cache: true
    - name: Run flutter doctor
      shell: bash
      run: flutter doctor
    - name: Decrypt SignETS certificate and Google Services files
      shell: bash
      run: |
        chmod +x ./scripts/decrypt.sh
        ./scripts/decrypt.sh
      env:
        ENCRYPTED_SIGNETS_API_CERT_PASSWORD: ${{ inputs.ENCRYPTED_SIGNETS_API_CERT_PASSWORD }}
        ENCRYPTED_GOOGLE_SERVICE_PASSWORD: ${{ inputs.ENCRYPTED_GOOGLE_SERVICE_PASSWORD }}
        ENCRYPTED_ETSMOBILE_KEYSTORE_PASSWORD: ${{ inputs.ENCRYPTED_ETSMOBILE_KEYSTORE_PASSWORD }}
        ENCRYPTED_KEYSTORE_PROPERTIES_PASSWORD: ${{ inputs.ENCRYPTED_KEYSTORE_PROPERTIES_PASSWORD }}

    # Get flutter dependencies.
    - name: Get flutter dependencies
      shell: bash
      run: flutter pub get
