version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dart"
      - "dependencies"
      - "version: Patch"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels:
      - "yaml"
      - "dependencies"
      - "version: Patch"