include: package:lint/analysis_options.yaml

linter:
  rules:
    sort_pub_dependencies: false
    directives_ordering: false
    require_trailing_commas: false
    depend_on_referenced_packages: false
analyzer:
  exclude:
    - "lib/generated"
    - "*.mocks.dart"
