include: package:flutter_lints/flutter.yaml

linter:
  rules:
analyzer:
  language:
    strict-casts: true
    # strict-inference: true
    # strict-raw-types: true
  exclude:
    - "lib/generated"
    - "*.mocks.dart"
