// Mocks generated by Mockito 5.4.4 from annotations
// in notredame/test/features/app/repository/mocks/quick_links_repository_mock.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:notredame/features/app/repository/quick_link_repository.dart'
    as _i2;
import 'package:notredame/features/ets/quick-link/models/quick_link.dart'
    as _i5;
import 'package:notredame/features/ets/quick-link/models/quick_link_data.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [QuickLinkRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockQuickLinkRepository extends _i1.Mock
    implements _i2.QuickLinkRepository {
  @override
  _i3.Future<List<_i4.QuickLinkData>> getQuickLinkDataFromCache() =>
      (super.noSuchMethod(
        Invocation.method(
          #getQuickLinkDataFromCache,
          [],
        ),
        returnValue:
            _i3.Future<List<_i4.QuickLinkData>>.value(<_i4.QuickLinkData>[]),
        returnValueForMissingStub:
            _i3.Future<List<_i4.QuickLinkData>>.value(<_i4.QuickLinkData>[]),
      ) as _i3.Future<List<_i4.QuickLinkData>>);

  @override
  _i3.Future<void> updateQuickLinkDataToCache(
          List<_i5.QuickLink>? quickLinkList) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateQuickLinkDataToCache,
          [quickLinkList],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  List<_i5.QuickLink> getDefaultQuickLinks(dynamic intl) => (super.noSuchMethod(
        Invocation.method(
          #getDefaultQuickLinks,
          [intl],
        ),
        returnValue: <_i5.QuickLink>[],
        returnValueForMissingStub: <_i5.QuickLink>[],
      ) as List<_i5.QuickLink>);
}
