name: "CI Build"
description: "Build the application on the CI"
inputs:
  target:
    description: The target OS {iOS, Android}
    required: true
  build-target:
    description: The build target {ios or apk}
    required: true
  build-args:
    description: The arguments for flutter build
    required: false
  build-path:
    required: true
  asset-extension:
    required: true
    default: zip
  app-name:
    required: true
  app-path:
    required: true
  maps-api-key:
    required: false
  app-hash:
    required: true
  
runs:
  using: "composite"
  steps:
    - name: Build the application
      shell: bash
      run: flutter build ${{ inputs.build-target }} ${{ inputs.build-args }} --release
      env:
        MAPS_API_KEY: ${{ inputs.maps-api-key }}
        APP_HASH: ${{ inputs.app-hash }}
    
    - name: Rename Android build
      if: inputs.target == 'Android'
      shell: bash
      run: mv app-release.${{ inputs.asset-extension }} ${{ inputs.app-path }}
      working-directory: ${{ inputs.build-path }}

    - name: Compress iOS build
      if: inputs.target == 'iOS'
      shell: bash
      run: |
        mv Runner.app ${{ inputs.app-name }}.app
        ditto -c -k --sequesterRsrc --keepParent ${{ inputs.app-name }}.app ${{ inputs.app-path }}
      working-directory: ${{ inputs.build-path }}

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.target }}
        path: ${{ inputs.app-path }}