// Mocks generated by Mockito 5.4.4 from annotations
// in notredame/test/features/app/error/internal_info_service_mock.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

// Dart imports:
import 'dart:async' as _i4;

// Package imports:
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:package_info_plus/package_info_plus.dart' as _i2;

// Project imports:
import 'package:notredame/features/app/error/internal_info_service.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePackageInfo_0 extends _i1.SmartFake implements _i2.PackageInfo {
  _FakePackageInfo_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [InternalInfoService].
///
/// See the documentation for Mockito's code generation for more information.
class MockInternalInfoService extends _i1.Mock
    implements _i3.InternalInfoService {
  @override
  _i4.Future<String> getDeviceInfoForErrorReporting() => (super.noSuchMethod(
        Invocation.method(
          #getDeviceInfoForErrorReporting,
          [],
        ),
        returnValue: _i4.Future<String>.value(_i5.dummyValue<String>(
          this,
          Invocation.method(
            #getDeviceInfoForErrorReporting,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<String>.value(_i5.dummyValue<String>(
          this,
          Invocation.method(
            #getDeviceInfoForErrorReporting,
            [],
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<_i2.PackageInfo> getPackageInfo() => (super.noSuchMethod(
        Invocation.method(
          #getPackageInfo,
          [],
        ),
        returnValue: _i4.Future<_i2.PackageInfo>.value(_FakePackageInfo_0(
          this,
          Invocation.method(
            #getPackageInfo,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.PackageInfo>.value(_FakePackageInfo_0(
          this,
          Invocation.method(
            #getPackageInfo,
            [],
          ),
        )),
      ) as _i4.Future<_i2.PackageInfo>);
}
