// Mocks generated by Mockito 5.4.4 from annotations
// in notredame/test/features/app/storage/mocks/preferences_service_mock.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

// Dart imports:
import 'dart:async' as _i4;

// Package imports:
import 'package:mockito/mockito.dart' as _i1;

// Project imports:
import 'package:notredame/constants/preferences_flags.dart' as _i3;
import 'package:notredame/features/app/storage/preferences_service.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [PreferencesService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPreferencesService extends _i1.Mock
    implements _i2.PreferencesService {
  @override
  List<_i3.PreferencesFlag> get persistentsKey => (super.noSuchMethod(
        Invocation.getter(#persistentsKey),
        returnValue: <_i3.PreferencesFlag>[],
        returnValueForMissingStub: <_i3.PreferencesFlag>[],
      ) as List<_i3.PreferencesFlag>);

  @override
  _i4.Future<bool> setBool(
    _i3.PreferencesFlag? flag, {
    required bool? value,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setBool,
          [flag],
          {#value: value},
        ),
        returnValue: _i4.Future<bool>.value(false),
        returnValueForMissingStub: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> setString(
    _i3.PreferencesFlag? flag,
    String? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setString,
          [
            flag,
            value,
          ],
        ),
        returnValue: _i4.Future<bool>.value(false),
        returnValueForMissingStub: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> setDynamicString(
    _i3.PreferencesFlag? flag,
    String? key,
    String? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setDynamicString,
          [
            flag,
            key,
            value,
          ],
        ),
        returnValue: _i4.Future<bool>.value(false),
        returnValueForMissingStub: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<void> clear() => (super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> clearWithoutPersistentKey() => (super.noSuchMethod(
        Invocation.method(
          #clearWithoutPersistentKey,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<Object?> getPreferencesFlag(_i3.PreferencesFlag? flag) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPreferencesFlag,
          [flag],
        ),
        returnValue: _i4.Future<Object?>.value(),
        returnValueForMissingStub: _i4.Future<Object?>.value(),
      ) as _i4.Future<Object?>);

  @override
  _i4.Future<bool> removePreferencesFlag(_i3.PreferencesFlag? flag) =>
      (super.noSuchMethod(
        Invocation.method(
          #removePreferencesFlag,
          [flag],
        ),
        returnValue: _i4.Future<bool>.value(false),
        returnValueForMissingStub: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> removeDynamicPreferencesFlag(
    _i3.PreferencesFlag? flag,
    String? key,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeDynamicPreferencesFlag,
          [
            flag,
            key,
          ],
        ),
        returnValue: _i4.Future<bool>.value(false),
        returnValueForMissingStub: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> setInt(
    _i3.PreferencesFlag? flag,
    int? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setInt,
          [
            flag,
            value,
          ],
        ),
        returnValue: _i4.Future<bool>.value(false),
        returnValueForMissingStub: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> setDateTime(
    _i3.PreferencesFlag? flag,
    DateTime? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setDateTime,
          [
            flag,
            value,
          ],
        ),
        returnValue: _i4.Future<bool>.value(false),
        returnValueForMissingStub: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool?> getBool(_i3.PreferencesFlag? flag) => (super.noSuchMethod(
        Invocation.method(
          #getBool,
          [flag],
        ),
        returnValue: _i4.Future<bool?>.value(),
        returnValueForMissingStub: _i4.Future<bool?>.value(),
      ) as _i4.Future<bool?>);

  @override
  _i4.Future<int?> getInt(_i3.PreferencesFlag? flag) => (super.noSuchMethod(
        Invocation.method(
          #getInt,
          [flag],
        ),
        returnValue: _i4.Future<int?>.value(),
        returnValueForMissingStub: _i4.Future<int?>.value(),
      ) as _i4.Future<int?>);

  @override
  _i4.Future<String?> getString(_i3.PreferencesFlag? flag) =>
      (super.noSuchMethod(
        Invocation.method(
          #getString,
          [flag],
        ),
        returnValue: _i4.Future<String?>.value(),
        returnValueForMissingStub: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);

  @override
  _i4.Future<String?> getDynamicString(
    _i3.PreferencesFlag? flag,
    String? key,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDynamicString,
          [
            flag,
            key,
          ],
        ),
        returnValue: _i4.Future<String?>.value(),
        returnValueForMissingStub: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);

  @override
  _i4.Future<DateTime?> getDateTime(_i3.PreferencesFlag? flag) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDateTime,
          [flag],
        ),
        returnValue: _i4.Future<DateTime?>.value(),
        returnValueForMissingStub: _i4.Future<DateTime?>.value(),
      ) as _i4.Future<DateTime?>);
}
