// Mocks generated by Mockito 5.4.4 from annotations
// in notredame/test/features/app/integration/mocks/networking_service_mock.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:connectivity_plus/connectivity_plus.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:notredame/features/app/integration/networking_service.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [NetworkingService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkingService extends _i1.Mock implements _i2.NetworkingService {
  @override
  _i3.Stream<List<_i4.ConnectivityResult>> get onConnectivityChanged =>
      (super.noSuchMethod(
        Invocation.getter(#onConnectivityChanged),
        returnValue: _i3.Stream<List<_i4.ConnectivityResult>>.empty(),
        returnValueForMissingStub:
            _i3.Stream<List<_i4.ConnectivityResult>>.empty(),
      ) as _i3.Stream<List<_i4.ConnectivityResult>>);

  @override
  _i3.Future<bool> hasConnectivity() => (super.noSuchMethod(
        Invocation.method(
          #hasConnectivity,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
        returnValueForMissingStub: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<String> getConnectionType() => (super.noSuchMethod(
        Invocation.method(
          #getConnectionType,
          [],
        ),
        returnValue: _i3.Future<String>.value(_i5.dummyValue<String>(
          this,
          Invocation.method(
            #getConnectionType,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i3.Future<String>.value(_i5.dummyValue<String>(
          this,
          Invocation.method(
            #getConnectionType,
            [],
          ),
        )),
      ) as _i3.Future<String>);
}
