# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :deploy do
    sh 'flutter build ipa --release --dart-define=GH_API_TOKEN=$GH_API_TOKEN'
    upload_to_add_store(
        ipa: '../build/ios/archive/Runner.xcarchive'
    )
  end
end
