// Mocks generated by Mockito 5.4.4 from annotations
// in notredame/test/features/app/navigation/navigation_service_mock.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

// Dart imports:
import 'dart:async' as _i5;

// Flutter imports:
import 'package:flutter/material.dart' as _i3;

// Package imports:
import 'package:mockito/mockito.dart' as _i1;

import 'package:notredame/features/app/analytics/remote_config_service.dart'
    as _i2;
import 'package:notredame/features/app/navigation/navigation_service.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeRemoteConfigService_0 extends _i1.SmartFake
    implements _i2.RemoteConfigService {
  _FakeRemoteConfigService_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGlobalKey_1<T extends _i3.State<_i3.StatefulWidget>>
    extends _i1.SmartFake implements _i3.GlobalKey<T> {
  _FakeGlobalKey_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [NavigationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNavigationService extends _i1.Mock implements _i4.NavigationService {
  @override
  _i2.RemoteConfigService get remoteConfigService => (super.noSuchMethod(
        Invocation.getter(#remoteConfigService),
        returnValue: _FakeRemoteConfigService_0(
          this,
          Invocation.getter(#remoteConfigService),
        ),
        returnValueForMissingStub: _FakeRemoteConfigService_0(
          this,
          Invocation.getter(#remoteConfigService),
        ),
      ) as _i2.RemoteConfigService);

  @override
  _i3.GlobalKey<_i3.NavigatorState> get navigatorKey => (super.noSuchMethod(
        Invocation.getter(#navigatorKey),
        returnValue: _FakeGlobalKey_1<_i3.NavigatorState>(
          this,
          Invocation.getter(#navigatorKey),
        ),
        returnValueForMissingStub: _FakeGlobalKey_1<_i3.NavigatorState>(
          this,
          Invocation.getter(#navigatorKey),
        ),
      ) as _i3.GlobalKey<_i3.NavigatorState>);

  @override
  bool pop() => (super.noSuchMethod(
        Invocation.method(
          #pop,
          [],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i5.Future<dynamic> pushNamed(
    String? routeName, {
    dynamic arguments,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #pushNamed,
          [routeName],
          {#arguments: arguments},
        ),
        returnValue: _i5.Future<dynamic>.value(),
        returnValueForMissingStub: _i5.Future<dynamic>.value(),
      ) as _i5.Future<dynamic>);

  @override
  _i5.Future<dynamic> pushNamedAndRemoveUntil(
    String? routeName, [
    String? removeUntilRouteNamed = r'/dashboard',
    Object? arguments,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #pushNamedAndRemoveUntil,
          [
            routeName,
            removeUntilRouteNamed,
            arguments,
          ],
        ),
        returnValue: _i5.Future<dynamic>.value(),
        returnValueForMissingStub: _i5.Future<dynamic>.value(),
      ) as _i5.Future<dynamic>);
}
