default_platform(:android)

platform :android do
  desc "Deploy a new version to the Google Play"
  lane :deploy do
    upload_to_play_store(
        aab: '../build/app/outputs/bundle/release/app-release.aab'
    )
  end
end
