// Mocks generated by Mockito 5.4.4 from annotations
// in notredame/test/features/app/widgets/mocks/app_widget_service_mock.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

// Dart imports:
import 'dart:async' as _i3;

// Package imports:
import 'package:mockito/mockito.dart' as _i1;

// Project imports:
import 'package:notredame/constants/widget_helper.dart' as _i5;
import 'package:notredame/features/app/widgets/app_widget_service.dart' as _i2;
import 'package:notredame/features/student/grades/widget_models.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [AppWidgetService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppWidgetService extends _i1.Mock implements _i2.AppWidgetService {
  @override
  _i3.Future<bool?> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i3.Future<bool?>.value(),
        returnValueForMissingStub: _i3.Future<bool?>.value(),
      ) as _i3.Future<bool?>);

  @override
  _i3.Future<bool?> sendProgressData(
          _i4.ProgressWidgetData? progressWidgetData) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendProgressData,
          [progressWidgetData],
        ),
        returnValue: _i3.Future<bool?>.value(),
        returnValueForMissingStub: _i3.Future<bool?>.value(),
      ) as _i3.Future<bool?>);

  @override
  _i3.Future<bool?> sendGradesData(_i4.GradesWidgetData? gradeWidgetData) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendGradesData,
          [gradeWidgetData],
        ),
        returnValue: _i3.Future<bool?>.value(),
        returnValueForMissingStub: _i3.Future<bool?>.value(),
      ) as _i3.Future<bool?>);

  @override
  _i3.Future<bool?> updateWidget(_i5.WidgetType? type) => (super.noSuchMethod(
        Invocation.method(
          #updateWidget,
          [type],
        ),
        returnValue: _i3.Future<bool?>.value(),
        returnValueForMissingStub: _i3.Future<bool?>.value(),
      ) as _i3.Future<bool?>);
}
