name: Add artifacts links to pull request and related issues.
on:
  workflow_run:
    workflows:
      - "Main workflow"
    types:
      - completed
jobs:
  artifacts_url_comments:
    name:  Add artifacts links to pull request and related issues.
    runs-on: ubuntu-latest
    steps:
      - uses: tonyhallett/artifacts-url-comments@v1.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          pullState: open
          prefix: 'Here you can find the latest builds:'
          suffix: . Be aware this link will be useable for ${{ github.retention_days }} days.
          format: name
          addTo: pullandissues
          errorNoArtifacts: false
