name: Test Version workflow
on:
  workflow_dispatch:
  pull_request:

jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
      - name: release label
        uses: actions-ecosystem/action-release-label@v1.2.0
        id: release-label
        with:
          label_prefix: "version: "
      - name: get latest tag
        needs:
          - release-label
        uses: actions-ecosystem/action-get-latest-tag@v1.6.0
        id: get-latest-tag
        if: ${{ steps.release-label.outputs.level != null }}
      - name: bump-semver
        needs:
          - get-latest-tag
        uses: actions-ecosystem/action-bump-semver@v1.0.0
        id: bump-semver
        if: ${{ steps.get-latest-tag.outputs.level != null }}
        with:
          current_version: ${{ steps.get-latest-tag.outputs.tag }}
          level: ${{ steps.release-label.outputs.level }}
      - name: Set pubspec version
        needs:
          - bump-semver
        if: ${{ steps.bump-semver.outputs.level != null }}
        run: echo ${{ steps.bump-semver.outputs.new_version }}
