name: Analyze, Test and Format
on: pull_request
jobs:
  build:
    name: Analyze and testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - name: Install OpenSSL
        run: sudo apt-get install openssl
      - name: Decrypt certificates files
        run: |
          chmod +x ./scripts/decrypt.sh
          ./scripts/decrypt.sh
        env:
          ENCRYPTED_SIGNETS_API_CERT_PASSWORD: ${{ secrets.ENCRYPTED_SIGNETS_API_CERT_PASSWORD }}
          MAPS_API_KEY: ${{ secrets.MAPS_API_KEY }}
      - run: flutter pub get
      # TODO: Commented until https://github.com/localizely/intl_utils/issues/26 is resolved. For now, please use the intl plugin for IDEA or VS Code
      #- run: flutter pub run intl_utils:generate
      - run: flutter analyze
      - run: flutter test
