name: Dev tools workflow
on:
  workflow_dispatch:
  pull_request:
    # paths-ignore:
    #   - '.gitignore'
    #   - '.metadata'
    #   - '.github/**'
    #   - '.githooks/**'
    #   - '*.md'
    #   - 'android/fastlane/**'
    #   - 'ios/fastlane/**'
    # types: [ labeled ]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  ##############################################################
  # Setup
  ##############################################################
  bump_version:
    name: Bump app version using PR labels
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.PTA }}
      - name: Get latest tag
        id: get_latest_tag
        run: |
          git fetch --tags
          latest_tag=$(git describe --abbrev=0 --tags || true)
          echo "Latest tag: ${latest_tag}"

    # name: Bump app version using PR labels
    # runs-on: ubuntu-latest
    # # The version label can't contain a ":" because of the YAML specification
    # if: ${{ github.event_name == 'pull_request' && !contains(github.event.pull_request.labels.*.name, 'version - Unversioned') }}
    # steps:
    #   - uses: actions/checkout@v4
    #     with:
    #       token: ${{ secrets.PTA }}
    #   - name: Bump version using labels
    #     uses: apomalyn/bump-version-using-labels@v1.5.0
    #     with:
    #       file_path: 'pubspec.yaml'
    #       reference_branch: 'master'
    #       commit: 'false'
    #   - name: Commit versioned files
    #     id: commit_version
    #     uses: stefanzweifel/git-auto-commit-action@v5
    #     with:
    #       file_pattern: "*.yaml"
    #       commit_user_name: github-actions[bot]
    #       commit_user_email: 41898282+github-actions[bot]@users.noreply.github.com
    #       commit_message: "[BOT] Applying version."
    #       add_options: '-u'
