name: Dev tools workflow
on:
  workflow_dispatch:
  pull_request:
    # paths-ignore:
    #   - '.gitignore'
    #   - '.metadata'
    #   - '.github/**'
    #   - '.githooks/**'
    #   - '*.md'
    #   - 'android/fastlane/**'
    #   - 'ios/fastlane/**'
    # types: [ labeled ]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  ##############################################################
  # Setup
  ##############################################################
  check-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.PTA }}

      - uses: actions-ecosystem/action-release-label@v1.2.0
        id: release-label
      - run: echo "action-release-label ${{ steps.release-label.outputs.level }}"

      - uses: actions-ecosystem/action-get-latest-tag@v1.6.0
        id: get-latest-tag
        if: ${{ steps.release-label.outputs.level != null }}
      - run: echo "get-latest-tag ${{ steps.get-latest-tag.outputs.tag }}"

      - uses: actions-ecosystem/action-bump-semver@v1
        id: bump-semver
        if: ${{ steps.release-label.outputs.level != null }}
        with:
          current_version: ${{ steps.get-latest-tag.outputs.tag }}
          level: ${{ steps.release-label.outputs.level }}
      - run: echo "bump-semver ${{ steps.bump-semver.outputs.new_version }}"
      


    # name: Bump app version using PR labels
    # runs-on: ubuntu-latest
    # # The version label can't contain a ":" because of the YAML specification
    # if: ${{ github.event_name == 'pull_request' && !contains(github.event.pull_request.labels.*.name, 'version - Unversioned') }}
    # steps:
    #   - uses: actions/checkout@v4
    #     with:
    #       token: ${{ secrets.PTA }}
    #   - name: Bump version using labels
    #     uses: apomalyn/bump-version-using-labels@v1.5.0
    #     with:
    #       file_path: 'pubspec.yaml'
    #       reference_branch: 'master'
    #       commit: 'false'
    #   - name: Commit versioned files
    #     id: commit_version
    #     uses: stefanzweifel/git-auto-commit-action@v5
    #     with:
    #       file_pattern: "*.yaml"
    #       commit_user_name: github-actions[bot]
    #       commit_user_email: 41898282+github-actions[bot]@users.noreply.github.com
    #       commit_message: "[BOT] Applying version."
    #       add_options: '-u'
